services:
  lambda:
    build: .
    command: index.handler
    network_mode: bridge
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_ENV_EXPORT: ${AWS_ENV_EXPORT}
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./test:/var/task
