services:
  lambda:
    build: .
    command: index.handler
    network_mode: bridge
    environment:
      AWS_ENV_EXPORT: ${AWS_ENV_EXPORT:-ssm://my/path/}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_LAMBDA_EXEC_WRAPPER: /opt/aws-env
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./test:/var/task
